### PR TITLE
Reduce APK/Bundle Size

### PR DESCRIPTION
**Pull request by jigar-f**
- [x] Remove unused kotlin/java code
- [x] Remove unused resources from Android project
- [ ] Try to find a way to reduce APK size
- [ ] Test changes thoroughly with all files removed

### CODE REVIEW

**Comment by jigar-f** [comment]
After removing these files and unused code, earlier @atavism made some changes on this that brings down the app size to 90MB.

 I generated a build with the following
- with `make android-release ANDROID_ARCH=all` I am getting a 210 MB build (@atavism Did you get 90 MB for all arch or just for 32?)
- with all arch (make android-release ANDROID_ARCH=arm32) I am getting an 85 MB build (So this reduces build size by 5MB).
- with `make android-release ANDROID_ARCH=arm64` I am getting a 93 MB build.


cc @atavism @myleshorton

**Comment by atavism** [comment]
@jigar-f We don't need to include 32-bit support, that's been removed.

To build the 90MB apk, we just need to remove the x86 libraries, do `make android-release ANDROID_ARCH=arm64`, and none of these changes are actually necessary, right?

**Comment by jigar-f** [comment]
> @jigar-f Thanks for making these changes! I don't think we need to support arm32

That's good

> I am able to further reduce the APK size (to ~ 80MB) with these changes: https://github.com/getlantern/lantern-client/pull/1031 -- can you check how that works for you? We can combine it with your updates

Thanks for making chanegs, I will take look

**Comment by jigar-f** [comment]
With the latest changes including from #1031 

The APK size is now 75 MB. Still, there are some class.dex are there, I am trying to find how to get of that compose in android

cc @atavism 

Screenshot 2024-03-28 at 5 23 13 PM

**Comment by jigar-f** [comment]
Few libs (dex) take bit of space

- Compose (Even though we are not using it)
- Stipe in classes4.dex

**Comment by jigar-f** [comment]
I updated proguard-rules.pro, but it didn't make much difference, I also tried multiple solutions, none worked.

Screenshot 2024-03-29 at 5 03 47 PM

cc @atavism Do you have any insight on this? I think we have tried almost all solutions.

**Comment by atavism** [comment]
> The APK size is now 75 MB. Still, there are some class.dex is there, I am trying to find how to get down size such as that compose in Android and others

75MB seems like a significant enough improvement for now. Do we want to merge this, and maybe as a next step, try to reduce the size of the Go library?

```
apkanalyzer -h files list --download-size lantern-installer.apk
28.5MB	/lib/x86_64/
1.6MB	/lib/x86_64/libsqlcipher.so
411.7KB	/lib/x86_64/libsentry.so
5.2KB	/lib/x86_64/libsentry-android.so
333.3KB	/lib/x86_64/libopustool.so
109.2KB	/lib/x86_64/libmodpng.so
2.5MB	/lib/x86_64/libmodpdfium.so
289.9KB	/lib/x86_64/libmodft2.so
22.5KB	/lib/x86_64/libjniPdfium.so
**14.3MB	/lib/x86_64/libgojni.so**
4.8MB	/lib/x86_64/libflutter.so
324.8KB	/lib/x86_64/libc++_shared.so
3.9MB	/lib/x86_64/libapp.so
27.2MB	/lib/arm64-v8a/
1.4MB	/lib/arm64-v8a/libsqlcipher.so
371.7KB	/lib/arm64-v8a/libsentry.so
5.1KB	/lib/arm64-v8a/libsentry-android.so
293.7KB	/lib/arm64-v8a/libopustool.so
99.6KB	/lib/arm64-v8a/libmodpng.so
2.3MB	/lib/arm64-v8a/libmodpdfium.so
269.8KB	/lib/arm64-v8a/libmodft2.so
20.9KB	/lib/arm64-v8a/libjniPdfium.so
**13.6MB	/lib/arm64-v8a/libgojni.so**
4.7MB	/lib/arm64-v8a/libflutter.so
296.3KB	/lib/arm64-v8a/libc++_shared.so
3.9MB	/lib/arm64-v8a/libapp.so
```

**Comment by jigar-f** [comment]
`75MB seems like a significant enough improvement for now. Do we want to merge this, and maybe as a next step, try to reduce the size of the Go library?`
Cool, I think we might need to test this more Since I have removed a lot of resources and class, I want to make sure We didn't lose anything.  

Would you mind taking it out for a spin and seeing if it works well?

**Comment by atavism** [comment]
@jigar-f Sure, doing that now!

**Comment by atavism** [comment]
@jigar-f The app is working well for me with these changes! I tried navigating to different pages, browsing Replica content, turning the VPN on, etc.

**Comment by jigar-f** [comment]
Thanks, @atavism, Could you confirm whether the chat feature works well? I guess that will be the last to check, If that works well I am good with merging this to main

**Comment by atavism** [comment]
> Thanks, @atavism, Could you confirm whether the chat feature works well? I guess that will be the last to check, If that works well I am good with merging this to main

There were some chat resources that were deleted I added back here: https://github.com/getlantern/lantern-client/pull/1044

Chat is still disabled with these changes

**Comment by jigar-f** [comment]
Do you think we should enable chat and test new changes?

**Comment by atavism** [comment]
> Do you think we should enable chat and test new changes?

Yep, I just did that, and it's working well for me

**Pull request merged**
