### PR TITLE
Audit suggestion fixes

### PR DESCRIPTION
**Pull request by jigar-f**
- https://github.com/getlantern/engineering/issues/1125
- https://github.com/getlantern/engineering/issues/1121
- https://github.com/getlantern/engineering/issues/1126

### CODE REVIEW

**Comment by jigar-f** [comment]
@atavism This is ready to merge?

**Comment by jigar-f** [comment]
Do you mind taking a look at it?

**Comment by atavism** [comment]
@jigar-f Taking a look now!

**Comment by atavism** [comment]
LGTM!

**Pull request merged**
