### PR TITLE
update flashlight, change bandit to new dialer pkg

### PR DESCRIPTION
**Pull request by garmr-ulfr**

### CODE REVIEW

**Review by myleshorton — APPROVED** [review]
LGTM! This damn git lfs thing is so weird -- gonna try the SMUDGE trick in CI here too

**Comment by garmr-ulfr** [comment]
I should have waited until you fixed it :laughing:

**Comment by myleshorton** [comment]
All good -- yeah I think the go.sum file theoretically should have been ok but this whole git lfs thing is still confusing to me =)

**Comment by myleshorton** [comment]
This is ready to bring in from my perspective though --- took me a sec to get my environment back up for `lantern-client`, but it's running great for me.

**Comment by atavism** [comment]
@myleshorton @garmr-ulfr Just a heads up: I'm no longer able to build the Lantern library on Android with these changes (it's why we refrained from upgrading to Go 1.23):

```
go env -w 'GOPRIVATE=github.com/getlantern/*' && \
	go install golang.org/x/mobile/cmd/gomobile && \
	gomobile init && \
	gomobile bind \
	    -target=android \
		-tags='headless lantern' -o=liblantern-all.aar \
		-androidapi=23 \
		-ldflags="-X github.com/getlantern/lantern-client/internalsdk/common.RevisionDate=20241122.055227 -X github.com/getlantern/lantern-client/internalsdk/common.BuildDate=20241124.213632  -X github.com/getlantern/lantern-client/internalsdk/common.ApplicationVersion=9999.99.99" \
		 \
		github.com/getlantern/lantern-client/internalsdk github.com/getlantern/pathdb/testsupport github.com/getlantern/pathdb/minisql
gomobile: /Users/paul/go/bin/gobind -lang=go,java -outdir=/var/folders/j5/yrnkkcxx6wlcr7h2f574qfjc0000gn/T/gomobile-work-3089658625 -tags=headless,lantern github.com/getlantern/lantern-client/internalsdk github.com/getlantern/pathdb/testsupport github.com/getlantern/pathdb/minisql failed: exit status 1
no exported names in the package "github.com/getlantern/lantern-client/internalsdk"
no exported names in the package "github.com/getlantern/lantern-client/internalsdk"
no exported names in the package "github.com/getlantern/lantern-client/internalsdk"
no exported names in the package "github.com/getlantern/lantern-client/internalsdk"
```

There was a change in Go 1.23 that affects how gomobile processes packages so it's a known issue. As a temporary workaround, I think we need to revert to using Go 1.22.x again

**Comment by atavism** [comment]
Running into this issue as well:

```
gomobile: go build -tags headless,lantern -ldflags -X github.com/getlantern/lantern-client/internalsdk/common.RevisionDate=20241122.055227 -X github.com/getlantern/lantern-client/internalsdk/common.BuildDate=20241124.215119  -X github.com/getlantern/lantern-client/internalsdk/common.ApplicationVersion=9999.99.99 -buildmode=c-shared -o=/var/folders/j5/yrnkkcxx6wlcr7h2f574qfjc0000gn/T/gomobile-work-3112360054/android/src/main/jniLibs/armeabi-v7a/libgojni.so ./gobind failed: exit status 1
# gobind/gobind
link: github.com/wlynxg/anet: invalid reference to net.zoneCache
```

**Comment by garmr-ulfr** [comment]
@atavism does it build if you switch it back to go1.22? I've used some of the new go1.23 features but I don't remember which project that was.

**Pull request merged**
