### PR TITLE
Update flashlight

### PR DESCRIPTION
**Pull request by hwh33**
Flashlight contains fixes necessary to support reflect-to-site proxies

### CODE REVIEW

**Comment by atavism** [comment]
LGTM, but It sounds like there's still some issues using Go 1.22.6 on Android. I'm doing some testing now

**Comment by atavism** [comment]
I'm getting the following error. Looks like we need to update fronted as well? 

```
go env -w 'GOPRIVATE=github.com/getlantern/*' && \
	go install golang.org/x/mobile/cmd/gomobile && \
	gomobile init && \
	gomobile bind \
	    -target=android \
		-tags='headless lantern' -o=liblantern-all.aar \
		-androidapi=23 \
		-ldflags="-X github.com/getlantern/lantern-client/internalsdk/common.RevisionDate=20241212.175419 -X github.com/getlantern/lantern-client/internalsdk/common.BuildDate=20241212.200751  -X github.com/getlantern/lantern-client/internalsdk/common.ApplicationVersion=9999.99.99" \
		 \
		github.com/getlantern/lantern-client/internalsdk github.com/getlantern/pathdb/testsupport github.com/getlantern/pathdb/minisql
gomobile: go build -tags headless,lantern -ldflags -X github.com/getlantern/lantern-client/internalsdk/common.RevisionDate=20241212.175419 -X github.com/getlantern/lantern-client/internalsdk/common.BuildDate=20241212.200751  -X github.com/getlantern/lantern-client/internalsdk/common.ApplicationVersion=9999.99.99 -buildmode=c-shared -o=/var/folders/j5/yrnkkcxx6wlcr7h2f574qfjc0000gn/T/gomobile-work-1861287855/android/src/main/jniLibs/armeabi-v7a/libgojni.so ./gobind failed: exit status 1
# github.com/getlantern/lantern-client/internalsdk/ios
/Users/paul/go/src/github.com/getlantern/lantern-client/internalsdk/ios/config.go:413:10: undefined: fronted.Configure
/Users/paul/go/src/github.com/getlantern/lantern-client/internalsdk/ios/config.go:414:31: not enough arguments in call to fronted.NewFronted
	have (time.Duration)
	want (string, "github.com/refraction-networking/utls".ClientHelloID, string)
/Users/paul/go/src/github.com/getlantern/lantern-client/internalsdk/ios/config.go:415:6: invalid operation: operator ! not defined on ok (variable of type error)
```

**Comment by myleshorton** [comment]
yeah those fixes are all in the `myles/early-fronting` branch in this PR https://github.com/getlantern/lantern-client/pull/1257

**Comment by jigar-f** [comment]
We are already using v7.6.165 on the main. Closing this in favor of the main.

**Pull request closed without merging**
