### PR TITLE
Update project structure

### PR DESCRIPTION
**Pull request by jigar-f**
- I tried updating the folder structure since it was cluttered and messy, with things all over the place. I switched to a feature-based folder structure, which looks much cleaner and should be easier to maintain and understand.

- About first `common` folder, there is a lot to unpack there, so for now we can keep the same and slowly we migrate that into the widgets folder in core

Screenshot 2024-09-17 at 3 54 07 PM

### CODE REVIEW

**Comment by jigar-f** [comment]
@ atavism Please look at it and let me know what you think. Feel free to send any suggestions

**Comment by jigar-f** [comment]
@atavism Could you check this?

**Comment by atavism** [comment]
@jigar-f Thanks for making these changes. Looking great to me! Let me do some testing and I'll provide some additional feedback

**Comment by jigar-f** [comment]
@atavism Is everything works well?

**Comment by jigar-f** [comment]
@atavism If you are okay then, I like to merge this to #1175

**Comment by atavism** [comment]
@jigar-f Checking now

**Comment by atavism** [comment]
> @atavism If you are okay then, I like to merge this to https://github.com/getlantern/lantern-client/pull/1175

@jigar-f Working well for me on Android!

On macOS, I'm seeing one issue:

```
Finished, Bindings generated in /Users/paul/go/src/github.com/getlantern/lantern-client/./lib/generated_bindings.dart
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                              3.2s
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008112-000809843A08201E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00008112-000809843A08201E, name:My Mac }
/Users/paul/.pub-cache/hosted/pub.dev/flutter_inappwebview_macos-1.0.11/macos/Classes/InAppWebView/InAppWebView.swift:870:26: error: method does not override any method from its superclass
    public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil) {
                         ^
    open func evaluateJavaScript(_ javaScriptString: String, completionHandler: (@MainActor @Sendable (Any?, (any Error)?) -> Void)? = nil)
```

I think we need to keep the flutter_inappwebview_macos dependency override? Feel free to merge it otherwise!

**Pull request merged**
