### PR TITLE
Fix signal handler

### PR DESCRIPTION
**Pull request by atavism**
Fix: desktop app panics due to missing SA_ONSTACK signal

Resolves https://github.com/getlantern/engineering/issues/1504

Based on https://github.com/wailsapp/wails/pull/2152

### CODE REVIEW

**Comment by jigar-f** [comment]
Wooo, Thanks, I spent days searching for a fix.

**Review by jigar-f — COMMENTED** [review]
Changes LGTM, Let me test this and will merge soon.

**Comment by jigar-f** [comment]
@atavism It Seems like for me, the Issue is still persistence, I am still getting crashes.

```
signal 16 received but handler not on signal stack
mp.gsignal stack [0x14000084000 0x1400008c000], mp.g0 stack [0x16b7c0000 0x16b9c3000], sp=0x14000051078
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0x164965784?, 0x0?})
	runtime/panic.go:1023 +0x40 fp=0x14000050fd0 sp=0x14000050fa0 pc=0x163c3ecc0
runtime.sigNotOnStack(0x10, 0x14000051078, 0x14000080008)
	runtime/signal_unix.go:1065 +0x118 fp=0x14000051000 sp=0x14000050fd0 pc=0x163c59728
runtime.adjustSignalStack(0x10, 0x14000080008, 0x140000510a8)
	runtime/signal_unix.go:592 +0x25c fp=0x14000051070 sp=0x14000051000 pc=0x163c5858c
runtime.sigtrampgo(0x10, 0x14000051210, 0x14000051278)
	runtime/signal_unix.go:480 +0x8c fp=0x140000510f0 sp=0x14000051070 pc=0x163c580cc
runtime.sigtrampgo(0x10, 0x14000051210, 0x14000051278)
	<autogenerated>:1 +0x1c fp=0x14000051120 sp=0x140000510f0 pc=0x163c7e3fc
runtime.sigtramp()
	runtime/sys_darwin_arm64.s:227 +0x4c fp=0x140000511e0 sp=0x14000051120 pc=0x163c7cecc
```

**Comment by atavism** [comment]
@jigar-f Interesting, doesn't crash at all for me. This is after running..

```
make darwin ffigen && flutter run -d macOS
```
?

**Comment by atavism** [comment]
@jigar-f Can you see if the app is still crashing for you with [this change](https://github.com/getlantern/lantern-client/pull/1130/commits/2b39e1019567cf7fbdd4120b2f406a83f803bc7c)?

**Comment by atavism** [comment]
@jigar-f Can you see if the app is still crashing for you with [this change](https://github.com/getlantern/lantern-client/pull/1130/commits/8a3ef8c72d0bc8178e49863b9af0592837a37e6f)?

**Comment by atavism** [comment]
@jigar-f Could you please let me know the contents of your settings.yaml? Also, do you have any luck deleting the Lantern home directory (`~/Library/Application\ Support/Lantern`) first?

**Comment by atavism** [comment]
@jigar-f I think I found another bug. It looks like we weren't checking for missing dialers when initializing bandit the first time and may be attempting to dial with a nil Dialer:

```
sync.(*Mutex).Lock(...)
	sync/mutex.go:90
github.com/getlantern/cmux/v2.(*dialer).Dial(0x14001abaa80, {0x1592d1490, 0x14001356230}, {0x0, 0x0}, {0x0, 0x0})
	github.com/getlantern/cmux/v2@v2.0.0-20230301223233-dac79088a4c0/dialer.go:53 +0xc0 fp=0x14003f110d0 sp=0x14003f10fd0 pc=0x1587d0d10
github.com/getlantern/cmux/v2.(*dialer).Dial-fm({0x1592d1490?, 0x14001356230?}, {0x0?, 0x15913ce80?}, {0x0?, 0x158d1f56c?})
	<autogenerated>:1 +0x54 fp=0x14003f11120 sp=0x14003f110d0 pc=0x1587d1fc4
github.com/getlantern/flashlight/v7/chained.(*multiplexedImpl).dialServer(0x159bc6dc8?, 0x1591164e0?, {0x1592d1490?, 0x14001356230?})
	github.com/getlantern/flashlight/v7@v7.6.90/chained/multiplexed_impl.go:51 +0x44 fp=0x14003f11160 sp=0x14003f11120 pc=0x158843014
github.com/getlantern/flashlight/v7/chained.dialOrigin.func1(0x140013bd700?)
	github.com/getlantern/flashlight/v7@v7.6.90/chained/dialer.go:181 +0x3c fp=0x14003f11190 sp=0x14003f11160 pc=0x15883f2fc
github.com/getlantern/flashlight/v7/chained.(*proxy).reportedDial(0x140004ec000, 0x14003f11388)
	github.com/getlantern/flashlight/v7@v7.6.90/chained/proxy.go:522 +0xf0 fp=0x14003f11280 sp=0x14003f11190 pc=0x158849320
github.com/getlantern/flashlight/v7/chained.dialOrigin(0x14003f11470, {0x1592d1490?, 0x14001356230?}, 0x140004ec000, {0x158d0ce44, 0x7}, {0x14003e1f527, 0x19})
	github.com/getlantern/flashlight/v7@v7.6.90/chained/dialer.go:180 +0x6c fp=0x14003f113b0 sp=0x14003f11280 pc=0x15883ed9c
github.com/getlantern/flashlight/v7/chained.(*proxy).DialContext(0x140004ec000, {0x1592d1490, 0x14001356230}, {0x158d0ce44, 0x7}, {0x14003e1f527, 0x19})
	github.com/getlantern/flashlight/v7@v7.6.90/chained/dialer.go:137 +0x264 fp=0x14003f114b0 sp=0x14003f113b0 pc=0x15883e554
github.com/getlantern/flashlight/v7/bandit.(*BanditDialer).DialContext(0x14000170fc0, {0x1592d1490, 0x14001356230}, {0x158d0ce44, 0x7}, {0x14003e1f527, 0x19})
	github.com/getlantern/flashlight/v7@v7.6.90/bandit/bandit.go:130 +0x260 fp=0x14003f116b0 sp=0x14003f114b0 pc=0x158534180
```

I'm wondering if you have any luck with the changes I just pushed (in particular the update to flashlight [here](https://github.com/getlantern/flashlight/tree/atavism/check-for-nil-dialers)? Thanks

**Comment by jigar-f** [comment]
That's great, that we found another bug, But, It's still crashing for me, Also I feel like it is something to do other code than go. Here is the [thread](https://wdynhnkxvsdx.slack.com/archives/C04T8M4AB1Q/p1721302298546809), But I am not so sure tho.


Also Here is the setting.yaml
```
addr: 127.0.0.1:57724
autoLaunch: true
autoReport: true
country: IN
googleAds: true
lang: en_us
localHTTPToken: ""
migratedDeviceIDForUserID: 0
proxyAll: false
salt: ""
socksAddr: 127.0.0.1:57726
systemProxy: true
uiAddr: ""
userFirstVisit: false
userID: 0
userLoggedIn: false
userPro: false
userToken: ""
```

**Comment by jigar-f** [comment]
Here is the method,

> This can only happen if non-Go code called sigaction without setting the SS_ONSTACK flag.

```
// This is called if we receive a signal when there is a signal stack
// but we are not on it. This can only happen if non-Go code called
// sigaction without setting the SS_ONSTACK flag.
func sigNotOnStack(sig uint32, sp uintptr, mp *m) {
	println("signal", sig, "received but handler not on signal stack")
	print("mp.gsignal stack [", hex(mp.gsignal.stack.lo), " ", hex(mp.gsignal.stack.hi), "], ")
	print("mp.g0 stack [", hex(mp.g0.stack.lo), " ", hex(mp.g0.stack.hi), "], sp=", hex(sp), "\n")
	throw("non-Go code set up signal handler without SA_ONSTACK flag")
}

```

**Comment by atavism** [comment]
This idletiming related stuff from the stack trace jumps out to me as well, but it may be a red herring:

```
	github.com/refraction-networking/utls@v1.3.3/conn.go:791 +0x40 fp=0x140000d27f0 sp=0x140000d27a0 pc=0x14d1ab470
bytes.(*Buffer).ReadFrom(0x1400095a638, {0x14df95b80, 0x14001b0e5a0})
	bytes/buffer.go:211 +0x90 fp=0x140000d2850 sp=0x140000d27f0 pc=0x14cdf17e0
github.com/refraction-networking/utls.(*Conn).readFromUntil(0x1400095a388, {0x11bfc8fc0, 0x14001996000}, 0x1?)
	github.com/refraction-networking/utls@v1.3.3/conn.go:813 +0xd0 fp=0x140000d2890 sp=0x140000d2850 pc=0x14d1ab650
github.com/refraction-networking/utls.(*Conn).readRecordOrCCS(0x1400095a388, 0x0)
	github.com/refraction-networking/utls@v1.3.3/conn.go:620 +0x224 fp=0x140000d2af0 sp=0x140000d2890 pc=0x14d1a8f24
github.com/refraction-networking/utls.(*Conn).readRecord(...)
	github.com/refraction-networking/utls@v1.3.3/conn.go:586
github.com/refraction-networking/utls.(*Conn).Read(0x1400095a388, {0x1400043b000, 0x1000, 0x14ea71a00?})
	github.com/refraction-networking/utls@v1.3.3/conn.go:1328 +0x168 fp=0x140000d2b60 sp=0x140000d2af0 pc=0x14d1ae6f8
github.com/getlantern/idletiming.(*IdleTimingConn).Read(0x14000235d90, {0x1400043b000, 0x1000, 0x1000})
	github.com/getlantern/idletiming@v0.0.0-20231030193830-6767b09f86db/idletiming_conn.go:147 +0x2ec fp=0x140000d2c60 sp=0x140000d2b60 pc=0x14d1f584c
net/http.(*persistConn).Read(0x14000825200, {0x1400043b000?, 0x140000d2d18?, 0x14cfd9180?})
	net/http/transport.go:1977 +0x50 fp=0x140000d2cc0 sp=0x140000d2c60 pc=0x14cfd82a0
```

**Comment by atavism** [comment]
Ok, I'm finally getting some useful information catching and handling the panic with panicwrap:

```
goroutine 209 gp=0x14000abbdc0 m=nil [select]:
runtime.gopark(0x14000a8af88?, 0x2?, 0x2?, 0x0?, 0x14000a8af54?)
	runtime/proc.go:402 +0xc8 fp=0x14000a8ae00 sp=0x14000a8ade0 pc=0x1680435b8
runtime.selectgo(0x14000a8af88, 0x14000a8af50, 0x1692d9118?, 0x0, 0x14000c81788?, 0x1)
	runtime/select.go:327 +0x614 fp=0x14000a8af10 sp=0x14000a8ae00 pc=0x168056b34
github.com/getlantern/lantern-client/desktop/ws.(*wsconn).write(0x14001525dd0)
	github.com/getlantern/lantern-client/desktop/ws/ws.go:197 +0x7c fp=0x14000a8afb0 sp=0x14000a8af10 pc=0x168b809fc
github.com/getlantern/lantern-client/desktop/ws.(*clientChannels).ServeHTTP.gowrap1()
	github.com/getlantern/lantern-client/desktop/ws/ws.go:107 +0x28 fp=0x14000a8afd0 sp=0x14000a8afb0 pc=0x168b7fd78
runtime.goexit({})
	runtime/asm_arm64.s:1222 +0x4 fp=0x14000a8afd0 sp=0x14000a8afd0 pc=0x16807dc34
created by github.com/getlantern/lantern-client/desktop/ws.(*clientChannels).ServeHTTP in goroutine 184
	github.com/getlantern/lantern-client/desktop/ws/ws.go:107 +0x3b4
```

**Comment by atavism** [comment]
Have a new PR for this https://github.com/getlantern/lantern-client/pull/1132

**Pull request closed without merging**
