### PR TITLE
Use flutter distributor to package Windows app

### PR DESCRIPTION
**Pull request by atavism**

### CODE REVIEW

**Comment by atavism** [comment]
This is almost ready for review. I need to test the build on a Windows machine yet

**Comment by jigar-f** [comment]
Let me know once its ready for review, I'll take look.

**Comment by atavism** [comment]
Feel free to take a look now, thanks @jigar-f!

**Review by jigar-f — APPROVED** [review]
Since I don't have windows, Chanegs are LGTM

**Comment by atavism** [comment]
Thanks so much for the review!

**Pull request merged**
