### PR TITLE
Add CLI program

### PR DESCRIPTION
**Pull request by atavism**
This PR adds a CLI program to support running Lantern without a UI. It includes options for configuring proxy addresses and using a local configuration

```
go build -o lantern-cli ./cli && ./lantern-cli --force-proxy-addr :8448 --stickyconfig true
DEBUG flashlight.common: const.go:69 ****************************** stagingMode: false
DEBUG flashlight.common: version.go:28 Flashlight version is 7.6.150
DEBUG flashlight.common: version.go:31 Setting LibraryVersion to 7.6.150
DEBUG flashlight.common: const.go:65 ****************************** stagingMode: false
DEBUG flashlight.common: version.go:34 Flashlight version is 7.6.150
DEBUG flashlight.common: version.go:37 Setting LibraryVersion to 7.6.150
DEBUG netx: netx.go:49 Enabling NAT64 auto-discovery
DEBUG netx: netx.go:53 Checking for updated NAT64 prefix
 INFO  Starting lantern: configDir %s /Users/paul/Library/Application Support/Lantern
 INFO  Using http proxy address: :8448
 INFO  Using socks proxy address: :0
DEBUG flashlight: flashlight.go:295 Running in app: Lantern
```

### CODE REVIEW

**Comment by atavism** [comment]
@hwh33 The CLI currently supports the flashlight flags as arguments ("force-proxy-addr", "stickyconfig", etc), but I have another PR here (WIP since we need to change a few things) to add support for extra arguments like setting the system proxy during start:

**Comment by Jovis7** [comment]
https://github.com/getlantern/engineering/issues/1779

**Review by hwh33 — APPROVED** [review]
There's a build error in the tests, but otherwise this looks good to me.  I tested this myself and was able to run Lantern from the command-line and use it as a local proxy.

**Comment by hwh33** [comment]
> I have another PR here (WIP since we need to change a few things) to add support for extra args like setting the system proxy during start: https://github.com/getlantern/lantern-client/pull/1261

You already closed the linked PR, but for what it's worth, we don't have a use case for this at the moment on the SDK team.

**Comment by atavism** [comment]
Thanks for the review, @hwh33! Test should be fixed now

**Pull request merged**
