### PR TITLE
Use flutter_distributor to package Lantern for Linux

### PR DESCRIPTION
**Pull request by atavism**
For https://github.com/getlantern/engineering/issues/1482

Packages for testing are up here: https://lantern.s3.amazonaws.com/lantern-installer-preview.deb and https://lantern.s3.amazonaws.com/lantern-installer-preview.rpm

- Linux ARM64 support
- RPM packaging support
- Deb packaging support
- Update sysproxy to latest version that supports Linux ARM64

image

### CODE REVIEW

**Comment by jigar-f** [comment]
@atavism thanks for jumping on this quickly.

**Comment by jigar-f** [comment]
Seems like the build is working fine, Should we merge this?

**Comment by atavism** [comment]
@jigar-f Thanks! Sounds good getting this merged since the build is working fine. I will do that shortly (just need to make a few changes and re-enable CI)

**Comment by atavism** [comment]
Ok, should be all set now

**Pull request merged**
