### PR TITLE
Support username/password on Android and desktop

### PR DESCRIPTION
**Pull request by atavism**
Resolves https://github.com/getlantern/engineering/issues/188 and https://github.com/getlantern/engineering/issues/189

### CODE REVIEW

**Comment by jigar-f** [comment]
@atavism I thought I was working on a desktop one.

**Comment by jigar-f** [comment]
Also, I thought, you were going to migrate Kotlin code to use a based mode in androidl, that way we will get all our features in go.

**Comment by atavism** [comment]
> @atavism I thought I was working on a desktop one, I actually started some work on that

Sorry, I thought the ticket was assigned to me? https://github.com/getlantern/engineering/issues/189

**Comment by jigar-f** [comment]
> Sorry, I thought the ticket was assigned to me? https://github.com/getlantern/engineering/issues/189

Sorry, I forgot to assign it to myself, I hope you did to lot on the desktop. You can go ahead and add it for Android please do.

> Migrating the Kotlin-based LanternHttpClient to Go is a separate task... why does that need to be migrated to add username/password support?

Sure, we can do that way as well,  I thought while we are at Kotlin we could do that, Like we did with the VPN model. but anyway we can do it later as well.

**Comment by atavism** [comment]
> Sure, we can do that way as well, I thought while we are at Kotlin we could do that, Like we did with the VPN model. but anyway we can do it later as well.

No, that's a great point. I am just wondering if we necessarily need to do that to support username/password on Android. Let me look into that.. 

I am not sure how far along you got with the desktop implementation, but if you point me to the branch you were working on, I can consolidate our changes on another branch if that would be useful. I think the most important change I wanted to make is to pull the auth methods out of the session model and into the auth client to make them easier to re-use elsewhere.

**Comment by jigar-f** [comment]
> No, that's a great point. I am just wondering if we necessarily need to do that to support username/password on Android. Let me look into that..

Yeah, username and password touch many points on the app so you might need to do quiet but on session moel, if you migrate to gomodel as we did with VPN it would be much easier to work and bug free

> I am not sure how far along you got with the desktop implementation, but if you point me to the branch you were working on, I can consolidate our changes for you to review if that would be useful. I think the most important change I wanted to make is to just pull the auth methods out of the session model and into the auth client to make them easier to re-use elsewhere.

Actually, I was using the same but this morning I saw your code as you did with SRP and I copied that page on my code. 😄 , My branch is [this](https://github.com/getlantern/lantern-client/tree/jigar/desktop-username-password)

**Comment by atavism** [comment]
> Actually, I was using the same but this morning I saw your code as you did with SRP and I copied that page on my code. 😄 , My branch is [this](https://github.com/getlantern/lantern-client/tree/jigar/desktop-username-password)

Oh, perfect! Thanks.. I'll take a look shortly. While we are testing username/password on desktop, I'm also gonna take a look at this one: https://github.com/getlantern/engineering/issues/1337

**Comment by jigar-f** [comment]
Yeah, That is perfect,

**Pull request closed without merging**
