### PR TITLE
Pub packages upgrade

### PR DESCRIPTION
**Pull request by jigar-f**

### CODE REVIEW

**Comment by jigar-f** [comment]
@atavism Take a look at this, I don't think we need any dependencies override anymore, also I update many other packages.

**Comment by jigar-f** [comment]
If you face an issue, try doing `flutter clean` before adding any dependencies override

**Comment by atavism** [comment]
Thanks for the tip about doing flutter clean first!

This is working well for me on macOS now.

**Comment by jigar-f** [comment]
@atavism Should I go ahead and merge this?

**Comment by atavism** [comment]
@jigar-f Let me do a bit more testing first just to make sure everything is working correctly, and then I'll merge it

**Comment by atavism** [comment]
Working well for me on macOS! Thanks again for making these changes. Love the new project structure!

**Pull request merged**
