### PR TITLE
Crash Rate fixes

### PR DESCRIPTION
**Pull request by jigar-f**
This PR fixes the below issues

> - Google Play Top crash related to crash while on transaction

The only way I can produce it is, I to run it multiple times and I will get that crash once in a while, I made some changes on android-db, Which might fix the issue, 

> Another issue with Error while commit

That is also fixed with this.

### CODE REVIEW

**Comment by jigar-f** [comment]
@atavism let's take our time with this and test it thoroughly, See if you can reproduce the crash or not

**Comment by atavism** [comment]
@jigar-f I just did some testing. Seems to be working well! One issue though I'm running into is that plans never load for some reason. I'm checking if it is an issue on main

Screenshot_20241004-073831

**Comment by atavism** [comment]
I'm seeing things like this in the logs as well, not sure if it's related or anything new

```
10-04 08:00:14.392 31256 31375 E Database: Error while commit
10-04 08:00:14.392 31256 31375 E Database: android.database.sqlite.SQLiteException: no such savepoint: 29ce9cb2-6015-401e-94f5-ecd360e9a659: RELEASE '29ce9cb2-6015-401e-94f5-ecd360e9a659'
10-04 08:00:14.392 31256 31375 E Database: 	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
10-04 08:00:14.392 31256 31375 E Database: 	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2442)
10-04 08:00:14.392 31256 31375 E Database: 	at io.lantern.model.dbadapter.TxAdapter.commit(DBAdapter.kt:58)
```

**Comment by jigar-f** [comment]
@atavism Seems strange, Let me look into it, Not sure how this is happening. I did a test yesterday no this.

**Comment by jigar-f** [comment]
@atavism Are you sure, You are now the latest code, I just uninstalled the app and tried again and did not see any error, Do you know the reproducible steps?, Even plans are showing for me.

**Comment by atavism** [comment]
> Are you sure, You are now the latest code, I just uninstalled the app and tried again and did not see any error, Do you know the reproducible steps? Even plans are showing for me.

Yes, I'm sure I pulled the latest changes. I uninstalled and installed the app multiple times and keep running into the same issue. Basically, I wait for Lantern to finish initializing and then I navigate to the plans page and see that error.

**Comment by atavism** [comment]
@jigar-f It may be unrelated to the updates here, which LGTM. I'll merge this and see if I can figure out the issue on my side

**Comment by jigar-f** [comment]
@atavism This PR is mainly for fixing issue you are getting, Not sure how you are still getting this.

**Pull request merged**
