### PR TITLE
Support username/password on Android 

### PR DESCRIPTION
**Pull request by atavism**
Also resolves https://github.com/getlantern/engineering/issues/1337

New PR that combines changes from https://github.com/getlantern/lantern-client/pull/1109 and https://github.com/getlantern/lantern-client/pull/1112

### CODE REVIEW

**Comment by atavism** [comment]
Screenshot_20240702-140401

@jigar-f The auth changes should be pretty close to working now on Android. Working through this error when I try to reset my password:

```
07-02 14:38:11.842 22521 22640 E BaseModel: Unexpected error calling signup: go.Universe$proxyerror: error while sign up Unexpected status code 400
07-02 14:38:11.842 22521 22629 I GoLog   : ERROR authclient: auth.go:101   at github.com/getlantern/lantern-client/internalsdk/auth.(*authClient).SignUp (srp.go:70)
07-02 14:38:11.842 22521 22629 I GoLog   : ERROR authclient: auth.go:101   at github.com/getlantern/lantern-client/internalsdk.(*authClient).SignUp (auth.go:43)
07-02 14:38:11.842 22521 22629 I GoLog   : ERROR authclient: auth.go:101   at main.proxyinternalsdk_AuthClient_SignUp (go_internalsdkmain.go:1774)
07-02 14:38:11.842 22521 22629 I GoLog   : ERROR authclient: auth.go:101   at _cgoexp_bffb5a40f3a3_proxyinternalsdk_AuthClient_SignUp (_cgo_gotypes.go:3761)
07-02 14:38:11.842 22521 22629 I GoLog   : ERROR authclient: auth.go:101   at runtime.cgocallbackg1 (cgocall.go:403)
07-02 14:38:11.842 22521 22629 I GoLog   : ERROR authclient: auth.go:101   at runtime.cgocallbackg (cgocall.go:322)
07-02 14:38:11.842 22521 22629 I GoLog   : ERROR authclient: auth.go:101   at runtime.cgocallback (asm_arm64.s:1130)
07-02 14:38:11.842 22521 22629 I GoLog   : ERROR authclient: auth.go:101   at runtime.goexit (asm_arm64.s:1222)
07-02 14:41:05.658 22521 22640 E BaseModel: Unexpected error calling signup: go.Universe$proxyerror: error while sign up Unexpected status code 400
07-02 14:41:05.670 22521 22593 I flutter : ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
07-02 14:41:05.670 22521 22593 I flutter : │ PlatformException(unknownError, error while sign up Unexpected status code 400, null, null)
07-02 14:41:05.670 22521 22593 I flutter : ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
07-02 14:41:05.670 22521 22593 I flutter : │ #0   StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
07-02 14:41:05.670 22521 22593 I flutter : │ #1   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
07-02 14:41:05.670 22521 22593 I flutter : │ #2   <asynchronous suspension>
07-02 14:41:05.670 22521 22593 I flutter : │ #3   _SignInState.createAccount (package:lantern/account/auth/sign_in.dart:167:7)
07-02 14:41:05.670 22521 22593 I flutter : │ #4   <asynchronous suspension>
07-02 14:41:05.670 22521 22593 I flutter : ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
07-02 14:41:05.670 22521 22593 I flutter : │ ⛔ Error while creating account
07-02 14:41:05.670 22521 22593 I flutter : └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

Screenshot_20240702-144107

**Comment by jigar-f** [comment]
@atavism If you want to reset your password then go to Sign in and then go to reset your password from there, Update Account is for only users who have never created an account with us.

**Comment by atavism** [comment]
> If you want to reset your password then go to Sign in and then go to reset your password from there, Update Account is for only users who have never created an account with us.

Ok, thanks for clarifying. I never created an account with that email but I was taken to the reset password screen when I clicked on the button to update my account.

**Comment by atavism** [comment]
@jigar-f I'm trying to test sign in with the test credentials (jigar+iosa@getlantern.org), and the auth client is returning an error that a salt "was not found calling api for jigar+iosa@getlantern.org".. Do you know what's causing that, and can you try testing these changes? Thanks

**Comment by atavism** [comment]
@jigar-f If I make my user Pro (I have no email or password) and go to Account -> Account Management -> Update Account 

This takes me to a page that to update my account. From here, I guess a temp account is created with a random password.

Whenever I try to do that though, I keep getting the following error that a "user with this legacy user ID already exists" -- do you know what this is about?

```
07-07 15:51:26.810 25026 25160 D org.getlantern.lantern.model.LanternSessionManager: Storing user data ProUser(userId=372989153, token=rVeBZREDZqC0GbOw91y4nFXgEdMNe6Zk2PjPBpg0lwaPfTXGGf8KsA, referral=8D6P25, email=, userStatus=active, code=8D6P25, locale=zh_CN, subscription=, expiration=1751927385, devices=[Device(id=1caafffda39f47bf, name=1caafffda39f47bf, created=1720391472)], userLevel=pro)
...
07-07 15:52:10.262 25026 25177 I GoLog   : Jul 07 22:52:10.261 - 0m44s ERROR defaultwebclient: response.go:66 Unexpected status code 400
07-07 15:52:10.262 25026 25177 I GoLog   :
07-07 15:52:10.262 25026 25177 I GoLog   :�,user with this legacy user ID already exists [error=Unexpected status code %d
07-07 15:52:10.262 25026 25177 I GoLog   :
07-07 15:52:10.262 25026 25177 I GoLog   : %v error_location=github.com/getlantern/lantern-client/internalsdk/webclient/defaultwebclient.SendToURL.func1 (rest.go:64) error_text=Unexpected status code 400
07-07 15:52:10.262 25026 25177 I GoLog   :
07-07 15:52:10.262 25026 25177 I GoLog   :�,user with this legacy user ID already exists error_type=errors.Error]
07-07 15:52:10.262 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at github.com/getlantern/lantern-client/internalsdk/webclient/defaultwebclient.SendToURL.func1 (rest.go:64)
07-07 15:52:10.263 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at github.com/getlantern/lantern-client/internalsdk/webclient.(*restClient).PostPROTOC (webclient.go:96)
07-07 15:52:10.263 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at github.com/getlantern/lantern-client/internalsdk/auth.(*authClient).signUp (auth.go:99)
07-07 15:52:10.263 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at github.com/getlantern/lantern-client/internalsdk/auth.(*authClient).SignUp (srp.go:70)
07-07 15:52:10.263 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at github.com/getlantern/lantern-client/internalsdk.(*authClient).SignUp (auth.go:43)
07-07 15:52:10.263 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at main.proxyinternalsdk_AuthClient_SignUp (go_internalsdkmain.go:1774)
07-07 15:52:10.263 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at _cgoexp_bffb5a40f3a3_proxyinternalsdk_AuthClient_SignUp (_cgo_gotypes.go:3761)
07-07 15:52:10.263 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at runtime.cgocallbackg1 (cgocall.go:403)
07-07 15:52:10.263 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at runtime.cgocallbackg (cgocall.go:322)
07-07 15:52:10.263 25026 25177 I GoLog   : ERROR defaultwebclient: response.go:66   at runtime.cgocallback (asm_arm64.s:
```

**Comment by jigar-f** [comment]
> @jigar-f I'm trying to test sign in with the test credentials ([jigar+iosa@getlantern.org](mailto:jigar+iosa@getlantern.org)), and the auth client is returning an error that a salt "was not found calling api for [jigar+iosa@getlantern.org](mailto:jigar+iosa@getlantern.org)".. Do you know what's causing that? Thanks

That is not an error, we first check if salt is in locale storage or not, If not then we call API.


> @jigar-f If I make my user Pro and go to Account -> Account Management -> Update Account, this takes me to a page that to update my account. From here, I guess a temp account is created with a random password.
> 
> Whenever I try to do that though, I keep getting the following error a "user with this legacy user ID already exists" -- do you know what this is about?

It seems, that this user id already has an account with some email email maybe.  Try reset password.

**Comment by jigar-f** [comment]
@atavism Do we still need this now that we have #1131, Do you think we can close this?

**Comment by atavism** [comment]
@jigar-f Sounds good! Let's merge https://github.com/getlantern/lantern-client/pull/1131 first and then we can re-open this if need be

**Pull request closed without merging**
